import type { ComponentType, SVGProps } from 'react'

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>

// PolyDesk uses one interface icon family. Brand marks remain custom SVGs.
export {
  BoltIcon as Activity,
  ArrowDownTrayIcon as Download,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathIcon as Loader2,
  ArrowRightIcon as ArrowRight,
  ArrowRightStartOnRectangleIcon as LogOut,
  ArrowTopRightOnSquareIcon as ExternalLink,
  ArrowTrendingDownIcon as TrendingDown,
  ArrowUpIcon as ArrowUp,
  ArrowUpRightIcon as ArrowUpRight,
  Bars3Icon as Menu,
  BeakerIcon as FlaskConical,
  BellAlertIcon as BellRing,
  BellIcon as Bell,
  BuildingOffice2Icon as Building2,
  ChartBarIcon as LineChart,
  ChatBubbleOvalLeftIcon as MessageCircle,
  CheckBadgeIcon as CheckCheck,
  CheckCircleIcon as CheckCircle2,
  CheckIcon as Check,
  ChevronDownIcon as ChevronDown,
  CircleStackIcon as Coins,
  ClockIcon as History,
  CpuChipIcon as Bot,
  CreditCardIcon as CreditCard,
  CurrencyDollarIcon as CircleDollarSign,
  DocumentDuplicateIcon as Copy,
  DocumentTextIcon as FileText,
  EnvelopeIcon as Mail,
  ExclamationTriangleIcon as TriangleAlert,
  GiftIcon as Gift,
  LockClosedIcon as LockKeyhole,
  MoonIcon as Moon,
  NewspaperIcon as Newspaper,
  PaperAirplaneIcon as Send,
  PencilIcon as Pencil,
  PlusCircleIcon as PlusCircle,
  PlusIcon as Plus,
  ShareIcon as Share2,
  ShieldCheckIcon as ShieldCheck,
  SignalIcon as Radar,
  SignalIcon as Radio,
  SparklesIcon as Sparkles,
  Squares2X2Icon as LayoutDashboard,
  StopIcon as Square,
  SunIcon as Sun,
  TrophyIcon as Trophy,
  UserCircleIcon as UserRound,
  UserGroupIcon as UsersRound,
  WalletIcon as Wallet,
  WalletIcon as WalletCards,
  XMarkIcon as X,
} from '@heroicons/react/24/outline'
