import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const layout = readFileSync(new URL('../src/layouts/PolyDeskLayout.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const tradeActivity = readFileSync(new URL('../src/pages/TradeActivity.tsx', import.meta.url), 'utf8')
const portfolioApi = readFileSync(new URL('../api/polymarket-portfolio.ts', import.meta.url), 'utf8')
const agentWorkspace = readFileSync(new URL('../src/pages/AgentWorkspace.tsx', import.meta.url), 'utf8')
const polyDeskPage = readFileSync(new URL('../src/pages/PolyDesk.tsx', import.meta.url), 'utf8')
const polyStream = readFileSync(new URL('../api/poly-stream.ts', import.meta.url), 'utf8')
const paymentLinks = readFileSync(new URL('../src/pages/TelegramPaymentLinks.tsx', import.meta.url), 'utf8')
const lpScoutPanel = readFileSync(new URL('../src/pages/LpScoutPanel.tsx', import.meta.url), 'utf8')
const lpScoutApi = readFileSync(new URL('../api/x402-polymarket-scout.ts', import.meta.url), 'utf8')
const pulsePage = readFileSync(new URL('../src/pages/Pulse.tsx', import.meta.url), 'utf8')
const pulseApi = readFileSync(new URL('../api/pulse.ts', import.meta.url), 'utf8')
const lpContextApi = readFileSync(new URL('../api/lp-context-intelligence.ts', import.meta.url), 'utf8')
const limitOrderTicket = readFileSync(new URL('../src/components/PolymarketLimitOrderTicket.tsx', import.meta.url), 'utf8')
const opportunityPage = readFileSync(new URL('../src/pages/Opportunity.tsx', import.meta.url), 'utf8')
const opportunityApi = readFileSync(new URL('../api/pulse-opportunity.ts', import.meta.url), 'utf8')
const opportunityImage = readFileSync(new URL('../src/lib/lpOpportunityShareImage.ts', import.meta.url), 'utf8')
const lpScoutReport = readFileSync(new URL('../src/pages/LPScoutReport.tsx', import.meta.url), 'utf8')
const dynamicSendButton = readFileSync(new URL('../src/components/DynamicSendButton.tsx', import.meta.url), 'utf8')
const agentIcon = readFileSync(new URL('../src/components/PolyDeskAgentIcon.tsx', import.meta.url), 'utf8')
const agentAskApi = readFileSync(new URL('../api/agent-ask.ts', import.meta.url), 'utf8')
const loadState = readFileSync(new URL('../src/components/PolyDeskLoadState.tsx', import.meta.url), 'utf8')
const productStyles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8')
const server = readFileSync(new URL('../server.ts', import.meta.url), 'utf8')
const packageJson = readFileSync(new URL('../package.json', import.meta.url), 'utf8')
const main = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8')
const productApp = readFileSync(new URL('../src/ProductApp.tsx', import.meta.url), 'utf8')
const viteConfig = readFileSync(new URL('../vite.config.ts', import.meta.url), 'utf8')
const rateLimit = readFileSync(new URL('../api/rate-limit.ts', import.meta.url), 'utf8')
const lpScoutReportApi = readFileSync(new URL('../api/lp-scout-report.ts', import.meta.url), 'utf8')
const agentActivityApi = readFileSync(new URL('../api/agent-activity-read.ts', import.meta.url), 'utf8')
const alertMonitor = readFileSync(new URL('../api/polymarket-alert-monitor.ts', import.meta.url), 'utf8')
const alertRules = readFileSync(new URL('../api/polymarket-alert-rules.ts', import.meta.url), 'utf8')
const emailProvider = readFileSync(new URL('../api/email-provider.ts', import.meta.url), 'utf8')

test('unresolved authentication restores once, then keeps the product publicly browsable', () => {
  const restoringGuard = layout.indexOf('if (!localPreview && (!ready || (authenticated && !walletsReady)))')
  assert.ok(restoringGuard >= 0)
  assert.match(layout, /Restoring your desk/)
  assert.match(layout, /import\.meta\.env\.DEV && searchParams\.get\('preview'\) === '1'/)
  assert.match(layout, /const previewMode = localPreview \|\| !authenticated/)
  assert.match(layout, /debugLabel="polydesk-header-sign-in"/)
  assert.doesNotMatch(layout, /if \(!localPreview && !authenticated\)/)
  assert.match(polyDeskPage, /const browsePreview = localPreview \|\| !user/)
})

test('refresh and route waits use one compact Polymarket sync state', () => {
  assert.match(layout, /<PolyDeskLoadingState fullScreen label="Restoring your desk" \/>/)
  assert.match(app, /<PolyDeskLoadingState fullScreen label="Opening PolyDesk" \/>/)
  assert.match(loadState, /MarketCardSkeleton/)
  assert.match(loadState, /animate-pulse/)
  assert.match(loadState, /PolymarketMark/)
  assert.doesNotMatch(loadState, />Loading|>Syncing|>Restoring|>Connecting|>Connect</)
  assert.doesNotMatch(layout, /Loading your session, wallet and workspace|PolyDeskRestoringScreen/)
  assert.doesNotMatch(paymentLinks, /Loading live board|Loading portfolio|Loading PolyDesk session/)
})

test('public Pulse defers wallet, agent and trading surfaces until they are opened', () => {
  assert.match(polyDeskPage, /lazy\(\(\) => import\('\.\/TelegramPaymentLinks'\)/)
  assert.match(polyDeskPage, /lazy\(\(\) => import\('\.\.\/components\/PolymarketLimitOrderTicket'\)/)
  assert.match(polyDeskPage, /PolyDeskLoadingState label="Opening workspace"/)
  assert.doesNotMatch(polyDeskPage, /import \{[^}]*PolyPortfolioPanel[^}]*\} from '\.\/TelegramPaymentLinks'/s)
  assert.match(pulsePage, /lazy\(\(\) => import\('\.\.\/components\/PolymarketLimitOrderTicket'\)/)
  assert.match(pulsePage, /PolyDeskLoadingState label="Opening order ticket"/)
})

test('workspace navigation keeps four primary destinations and nests Activity under Overview', () => {
  const primaryNav = layout.slice(layout.indexOf('const navItems = ['), layout.indexOf('] as const'))
  assert.match(layout, /label: 'Overview'/)
  assert.match(layout, /label: 'LP Scout'/)
  assert.match(layout, /label: 'Pulse'/)
  assert.match(layout, /label: 'Agent'/)
  assert.doesNotMatch(primaryNav, /\{ id: 'activity', label: 'Activity'/)
  assert.match(layout, /aria-label="Overview sections"/)
  assert.match(layout, /overviewSection === item\.id/)
  assert.match(layout, /inline-flex h-7 items-center/)
  assert.doesNotMatch(polyDeskPage, /sticky top-\[61px\]|function OverviewTabs/)
  assert.match(layout, /aria-label="PolyDesk workspace"/)
  assert.match(layout, /LayoutDashboard/)
  assert.match(layout, /Radar/)
  assert.match(layout, /PulseIcon/)
  assert.match(layout, /PolyDeskAgentIcon/)
  assert.match(layout, /fixed inset-x-0 bottom-0 z-50 border-t/)
  assert.doesNotMatch(layout, /<header[^>]+backdrop-blur|<footer[^>]+backdrop-blur/)
  assert.match(layout, /grid w-full max-w-2xl grid-cols-4/)
  assert.doesNotMatch(layout, /w-\[min\(26rem,calc\(100%-2rem\)\)\]/)
  assert.ok(layout.indexOf("label: 'Pulse'") < layout.indexOf("label: 'Overview'"))
  assert.match(layout, /service === 'portfolio' \|\| service === 'activity'/)
  assert.doesNotMatch(layout, /label: 'App Pay'|label: 'Trade'|label: 'Tip'|WorkspaceUtilityPill/)
  assert.match(polyDeskPage, /initialPortfolioAction="trading"/)
  assert.match(polyDeskPage, /legacyService !== 'app-pay' && legacyService !== 'marketplace'/)
})

test('PolyDesk Agent uses the extracted modern composer without category selection', () => {
  assert.match(polyDeskPage, /singlePolyDeskAgent/)
  assert.match(polyDeskPage, />PolyDesk Agent</)
  assert.match(paymentLinks, /!singlePolyDeskAgent/)
  assert.match(paymentLinks, /<DynamicSendButton/)
  assert.match(dynamicSendButton, /ArrowUp, Plus, Square/)
  assert.match(dynamicSendButton, /rounded-full/)
  assert.match(agentIcon, /polydesk-chat-icon__bubble/)
  assert.doesNotMatch(agentIcon, /__head|__eye|__antenna|__mouth/)
  assert.match(paymentLinks, /singlePolyDeskAgent \? inferredPolyDeskSubMode/)
  assert.match(polyDeskPage, /initialPayer=\{ownerKey\}/)
  assert.match(polyDeskPage, /identity:\$\{privyIdentity\}/)
  assert.match(polyDeskPage, /polydesk-preview-agent/)
  assert.match(agentAskApi, /polydesk-\(preview\|web\)/)
  assert.match(agentAskApi, /deepPolyDeskRequest/)
  assert.match(agentAskApi, /Deep market research is temporarily unavailable/)
  assert.match(paymentLinks, /technicalIdentity/)
  assert.match(paymentLinks, /Uses PolyDesk Agent for Polymarket portfolio/)
  assert.match(polyDeskPage, /welcomeAction=/)
  assert.match(polyDeskPage, /okx\.ai\/agents\/5427/)
  assert.match(polyDeskPage, /immersive/)
  assert.doesNotMatch(polyDeskPage, /overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-card/)
  assert.match(paymentLinks, /data-polydesk-live-score-widget/)
  assert.match(paymentLinks, /latest news\|headlines\?/)
  assert.match(paymentLinks, /data\.mode !== 'live'/)
  assert.match(layout, /mobileKeyboardOpen/)
  assert.match(layout, /workspace === 'agent' && mobileKeyboardOpen && 'hidden'/)
  assert.match(layout, /pb-\[calc\(4\.25rem\+env\(safe-area-inset-bottom\)\)\]/)
  assert.match(layout, /settledViewportHeight - viewport\.height > 120/)
  assert.match(layout, /document\.addEventListener\('focusin', updateKeyboardState\)/)
  assert.match(layout, /data-polydesk-keyboard-open=/)
  assert.doesNotMatch(layout, /window\.innerHeight - viewport\.height > 120/)
})

test('Overview exposes the existing watch and external funding routes as compact actions', () => {
  assert.match(polyDeskPage, /label: 'Watch portfolio'/)
  assert.match(polyDeskPage, /label: 'Tip'/)
  assert.match(polyDeskPage, /openPortfolioAction\('watch'\)/)
  assert.match(polyDeskPage, /openPortfolioAction\('external'\)/)
  assert.match(polyDeskPage, /Send USDC to a Polymarket wallet\./)
})

test('Pulse rotates verified liquidity intelligence without inventing provider data', () => {
  assert.match(pulsePage, /10_000/)
  assert.match(pulsePage, /PULSE_SESSION_MAX_AGE_MS = 10 \* 60_000/)
  assert.match(pulsePage, /sessionStorage\.setItem\(PULSE_SESSION_KEY/)
  assert.match(pulsePage, /if \(requestRef\.current\) return requestRef\.current/)
  assert.match(pulsePage, /response\.json\(\)\.catch\(\(\) => null\)/)
  assert.match(pulsePage, /document\.visibilityState === 'visible'/)
  assert.match(pulseApi, /STALE_CACHE_MS = 10 \* 60_000/)
  assert.match(pulseApi, /void refreshPulseFeed\(\)\.catch/)
  assert.match(pulseApi, /stale-while-revalidate=120/)
  assert.match(pulseApi, /Server-Timing/)
  assert.match(pulseApi, /X-PolyDesk-Pulse-Cache/)
  assert.match(pulsePage, /PolymarketLimitOrderTicket/)
  assert.match(pulsePage, /polydesk-card group relative block h-\[280px\]/)
  assert.doesNotMatch(pulsePage, /ShieldCheck|Human quote guide/)
  assert.doesNotMatch(pulsePage, /rounded-3xl bg-gray-950/)
  assert.match(pulseApi, /\.slice\(0, 3\)/)
  assert.match(pulseApi, /candidateLimit: 80, opportunityLimit: 10/)
  assert.match(pulseApi, /index === 0 \? 'Strongest opportunity'/)
  assert.match(pulsePage, /ordinal\(lead\.rank\)/)
  assert.match(pulsePage, /rankMedal\(index \+ 1\)/)
  assert.match(pulsePage, /markets\.slice\(0, 5\)/)
  assert.match(pulsePage, /🥇/)
  assert.match(pulsePage, /USDC minimum setup/)
  assert.doesNotMatch(pulseApi, /news:coming-soon|football:coming-soon/)
  assert.match(pulsePage, /A stronger qualifying market replaces the weakest/)
  assert.match(pulsePage, /ContextLabels/)
  assert.match(lpContextApi, /articleMatchesOpportunity/)
  assert.match(lpContextApi, /footballMatchMatchesOpportunity/)
  assert.doesNotMatch(pulsePage, />Trade</)
  assert.match(pulseApi, /marketUrl\?\.startsWith\('https:\/\/polymarket\.com\/event\/'\)/)
  assert.match(server, /app\.get\('\/api\/pulse', readLimiter, pulseHandler\)/)
  assert.match(server, /req\.query\.action \?\? req\.body\?\.action/)
  assert.match(server, /warmPulse\('startup'\)/)
  assert.match(server, /warmPulse\('scheduled'\)/)
  assert.match(server, /scheduledWarm\.unref\(\)/)
  assert.match(layout, /touch-manipulation/)
  assert.match(productStyles, /\[data-polydesk-product-ui\] :is\(button, a\)/)
})

test('LP order ticket separates projected risk, filled-position PnL and LP rewards', () => {
  assert.match(limitOrderTicket, /Max payout/)
  assert.match(limitOrderTicket, /Potential profit/)
  assert.match(limitOrderTicket, /Amount at risk/)
  assert.match(limitOrderTicket, /belowRewardMinimum/)
  assert.match(limitOrderTicket, /meet the displayed reward minimum/)
  assert.match(limitOrderTicket, /Estimated two-sided setup/)
  assert.match(limitOrderTicket, /action=positions/)
  assert.match(limitOrderTicket, /Live P&amp;L appears here after Polymarket matches the order/)
  assert.match(limitOrderTicket, /LP rewards settle separately/)
  assert.match(limitOrderTicket, /border-blue-600 bg-blue-600/)
  assert.match(limitOrderTicket, /border-red-600 bg-red-600/)
  assert.doesNotMatch(limitOrderTicket, /bg-gradient-to-br|shadow-\[0_8px_20px/)
  assert.match(limitOrderTicket, /action: 'register-lp-order'/)
  assert.match(limitOrderTicket, /action: 'mark-lp-order-cancelled'/)
  assert.doesNotMatch(limitOrderTicket, /Starting LP order monitoring|Set up portfolio monitoring from Overview/)
})

test('public LP opportunities use a stable share route and truthful Polymarket-style ticket', () => {
  assert.match(app, /path="\/opportunity\/:slug"/)
  assert.match(server, /app\.get\('\/api\/pulse\/opportunity\/:slug'/)
  assert.match(server, /app\.get\('\/opportunity\/:slug'/)
  assert.match(opportunityApi, /mode: 'market'/)
  assert.match(opportunityPage, /bg-\[#2f5bff\]/)
  assert.match(opportunityPage, /Daily market rewards/)
  assert.match(opportunityPage, /Suggested prices/)
  assert.match(opportunityPage, /Choose price and amount/)
  assert.match(pulsePage, /\/opportunity\/\$\{encodeURIComponent\(marketSlug\(selected\)\)\}/)
  assert.match(opportunityPage, /renderLpOpportunityPng/)
  assert.doesNotMatch(opportunityPage, /Download image|Share link/)
  assert.match(opportunityImage, /const WIDTH = 1080/)
  assert.match(opportunityImage, /const HEIGHT = 1350/)
  assert.match(opportunityImage, /image\/png/)
  assert.match(opportunityImage, /Daily rewards/)
  assert.match(opportunityImage, /Min setup/)
  assert.match(opportunityImage, /Choose a side, enter an amount, and wait for a match/)
  assert.match(opportunityImage, /View opportunity on PolyDesk/)
  assert.match(opportunityImage, /Rewards are shared across eligible liquidity providers/)
  assert.doesNotMatch(opportunityImage, /PRICE GAP|SHARES NEAR PRICE|SMALLEST ORDER|What to do|STEADY SETUP|WATCH PRICE|RISKY SETUP/)
  assert.doesNotMatch(opportunityPage, /inside the current|post-only/)
  assert.match(opportunityPage, /Your order will wait for someone to match it/)
  assert.match(limitOrderTicket, /Waits for a match/)
  assert.doesNotMatch(limitOrderTicket, /MAX_ORDER_USDC|safety-limited release/)
  assert.doesNotMatch(limitOrderTicket, /Live GTC|Confirm the GTC|rejected the GTC/)
  assert.match(limitOrderTicket, /step=\{tickSize\}/)
  assert.match(pulsePage, /tickSize=\{selected\.tickSize\}/)
})

test('paid LP Scout reports share a safe social image without payment or proof data', () => {
  assert.match(lpScoutReport, /renderLpOpportunityPng/)
  assert.match(lpScoutReport, /variant: 'report'/)
  assert.match(lpScoutReport, /Share insight/)
  assert.match(lpScoutReport, /navigator\.share/)
  assert.match(lpScoutReport, /service=lp-scout/)
  assert.match(opportunityImage, /Scout takeaway/)
  assert.match(opportunityImage, /Explore LP Scout on PolyDesk/)
  const sharePayload = lpScoutReport.slice(
    lpScoutReport.indexOf('async function shareInsight'),
    lpScoutReport.indexOf('return ('),
  )
  assert.doesNotMatch(sharePayload, /receiptUrl|proofHash|wallet|x402/)
  assert.doesNotMatch(sharePayload, /window\.location\.href/)
})

test('paid report APIs require the linked receipt capability and avoid private caching', () => {
  assert.match(lpScoutReportApi, /authorizedLpScoutReceipt/)
  assert.match(agentActivityApi, /authorizedLpScoutReceipt/)
  assert.match(lpScoutReportApi, /Cache-Control', 'no-store/)
  assert.match(agentActivityApi, /Cache-Control', 'no-store/)
  assert.doesNotMatch(lpScoutReportApi, /scout: scoutResult|zeroscout: zeroScout/)
  assert.match(agentWorkspace, /next\.set\('lpScoutReceipt'/)
  assert.match(paymentLinks, /receiptQuery/)
})

test('Trade Activity uses the saved account feed and completed LP Scout records', () => {
  assert.match(portfolioApi, /action === 'activity'/)
  assert.match(portfolioApi, /\/activity\?user=/)
  assert.match(tradeActivity, /polymarket-portfolio\?action=activity/)
  assert.match(tradeActivity, /readSavedLpScoutActivity/)
  assert.match(tradeActivity, /lp-scout-report/)
  assert.match(tradeActivity, /expandedActivityId/)
  assert.match(tradeActivity, /aria-expanded=\{expanded\}/)
  assert.match(tradeActivity, /Open on Polymarket/)
  assert.match(tradeActivity, /View report/)
  assert.match(tradeActivity, /searchParams\.get\('preview'\) === '1'/)
  assert.match(agentWorkspace, /rememberLpScoutActivity/)
  assert.doesNotMatch(tradeActivity, /row\.status|polydesk-card mt-6 overflow-hidden/)
})

test('public portfolio watches verify email ownership and use authoritative market transitions', () => {
  assert.match(portfolioApi, /alert_email_verified/)
  assert.match(portfolioApi, /create-public-watch/)
  assert.match(portfolioApi, /verify-public-watch/)
  assert.match(portfolioApi, /polymarket_public_watch_tokens/)
  assert.match(portfolioApi, /position\.percentPnl/)
  assert.match(alertRules, /belowThreshold && !input\.wasBelowThreshold/)
  assert.match(alertRules, /winningAssetId/)
  assert.match(alertMonitor, /event_type === 'market_resolved'/)
  assert.match(alertMonitor, /custom_feature_enabled: true/)
  assert.match(portfolioApi, /reconcilePolymarketResolutionAlerts/)
  assert.match(paymentLinks, /label="Market results"/)
  assert.match(paymentLinks, /label="Alert email"/)
  assert.match(paymentLinks, /label="New positions"/)
  assert.match(alertMonitor, /reconcilePolymarketWatchedPortfolios/)
  assert.match(alertMonitor, /reconcilePolymarketLpOrders/)
  assert.match(portfolioApi, /polymarket_lp_order_watch/)
  assert.match(portfolioApi, /lp-order-\$\{input\.lifecycle\}/)
  assert.match(paymentLinks, /Monitor my LP portfolio/)
  assert.match(paymentLinks, /Position and order alerts for this trading account/)
  assert.match(portfolioApi, /trackedLpAssets\.has\(assetId\)/)
  assert.doesNotMatch(paymentLinks, /Build env needed/)
  assert.match(paymentLinks, /usingStandaloneWatch/)
  assert.match(portfolioApi, /alert_email_verified = false/)
  assert.doesNotMatch(paymentLinks, /label="Live market movement"/)
  assert.doesNotMatch(portfolioApi, /ended < Date\.now\(\)/)
  assert.match(emailProvider, /EMAIL_TIMEOUT_MS/)
  assert.match(emailProvider, /TRANSIENT_STATUS/)
})

test('LP Scout checkout returns through the paid-result continuation on Arc Testnet', () => {
  assert.match(polyDeskPage, /lazy\(\(\) => import\('\.\/AgentWorkspace'\)\)/)
  assert.match(polyDeskPage, /serviceView === 'lp-scout' && searchParams\.get\('run'\) === 'polymarket-scout'/)
  assert.match(polyDeskPage, /<AgentWorkspace \/>/)
  assert.match(agentWorkspace, /const network = 'arc'/)
  assert.doesNotMatch(agentWorkspace, /network === 'base'/)
})

test('LP Scout keeps one focused best-market scan and one exact-market inspection path', () => {
  assert.match(layout, /LP Scout/)
  assert.match(lpScoutPanel, /Best opportunities/)
  assert.match(lpScoutPanel, /Inspect market/)
  assert.match(lpScoutPanel, /up to 10 ranked liquidity opportunities/)
  assert.doesNotMatch(lpScoutPanel, /Football markets|News markets|Coming soon/)
  assert.doesNotMatch(lpScoutPanel, /Choose a scout, set a max spend|Continue to LP Scout checkout|Scout a theme/)
  assert.match(polyStream, /POLY_STREAM_LEAGUE_IDS/)
  assert.match(polyStream, /Verified football board/)
  assert.match(lpScoutApi, /getPolyStreamFeed/)
  assert.match(lpScoutApi, /match\.polymarketUrl\.startsWith\('https:\/\/polymarket\.com\/event\/'\)/)
  assert.match(lpScoutApi, /Verified football provider plus Polymarket Gamma and CLOB public APIs/)
  assert.doesNotMatch(polyStream, /DEFAULT_WORLD_CUP_START_DATE|DEFAULT_FANVIBE_WORLD_CUP_FEED_URL|series_slug: 'soccer-fifwc'/)
})

test('the active LP Scout checkout is isolated from the legacy Telegram surface', () => {
  assert.match(polyDeskPage, /from '\.\/LpScoutPanel'/)
  assert.match(lpScoutPanel, /serviceUrl: '\/api\/x402\/polymarket-scout'/)
  assert.match(lpScoutPanel, /n: 'arc'/)
  assert.doesNotMatch(paymentLinks, /export function LpScoutPanel/)
})

test('active product surfaces share the premium CTA system without the legacy server marketplace', () => {
  assert.match(productStyles, /\.polydesk-primary-cta/)
  assert.match(productStyles, /min-height: 44px/)
  assert.match(productStyles, /\.polydesk-primary-cta--compact/)
  assert.match(productStyles, /\.polydesk-primary-cta:focus-visible/)
  assert.match(layout, /polydesk-primary-cta polydesk-primary-cta--compact/)
  assert.match(agentWorkspace, /polydesk-primary-cta mt-4 w-full/)
  assert.match(paymentLinks, /polydesk-primary-cta polydesk-primary-cta--compact shrink-0/)
  assert.match(paymentLinks, /polydesk-primary-cta w-full/)
  assert.doesNotMatch(server, /okx-agentic-marketplace|okx-marketplace-checkout|okxAgenticWalletReady/)
  assert.doesNotMatch(packageJson, /ensure-onchainos|test:okx-marketplace|smoke:okx-public-marketplace/)
})

test('the public shell avoids unused global providers and eval-capable browser polyfills', () => {
  assert.doesNotMatch(main, /QueryClientProvider|WagmiProvider|PrivyWagmiProvider/)
  assert.match(main, /lazy\(\(\) => import\('\.\/ProductApp'\)\)/)
  assert.match(productApp, /<PrivyProvider/)
  assert.doesNotMatch(productApp, /QueryClientProvider|WagmiProvider|PrivyWagmiProvider/)
  assert.match(viteConfig, /exclude: \['vm'\]/)
  assert.doesNotMatch(server, /unsafe-eval/)
  assert.doesNotMatch(server, /script-src[^"]*unsafe-inline/)
  assert.match(server, /runtime-config\.js/)
  assert.match(server, /app\.set\('trust proxy', 1\)/)
  assert.doesNotMatch(rateLimit, /x-forwarded-for/)
})
